version: "3"
services:
  noteapi:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: 3000
    expose:
      - 3000
    depends_on:
      - mongo
      - redis
      - nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
  mongo:
    image: mongo
    restart: unless-stopped
    expose:
      - 27017
  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379